services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./serverless.yml:/app/serverless.yml
    environment:
      - SERVERLESS_ACCESS_KEY=${SERVERLESS_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_TABLE=${DYNAMODB_TABLE}
